### ISSUE TITLE
Getting error after importing

### ISSUE THREAD

**Issue by jisuo** [lloydzhou/tsxecharts#7]
```
ReferenceError: exports is not defined
    at node_modules/rc-echart/lib/Chart.js (Chart.js:24:23)
    at __init (chunk-7REXU52E.js?v=eb06a9c8:16:56)
    at node_modules/rc-echart/lib/index.js (index.js:17:14)
    at __require2 (chunk-7REXU52E.js?v=eb06a9c8:19:50)
    at index.js:19:38
```
    

Line 24 in Chart.js is:
    
`Object.defineProperty(exports, "__esModule", { value: true });`
    

I have `"type": "module"` in package.json and tsconfig is:

```
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "types": ["vite/client", "vite-plugin-svgr/client"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "src"
  },
  "include": ["src"]
}

```
    
Not sure why it transpiled into CommonJs?

**Comment by TechQuery** [comment]
You can try ECharts Web components library: https://github.com/idea2app/ECharts-JSX
